name: Generate and upload PDF

on:
  push:
    branches:
    - main

jobs:
  build-pdf:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install dependencies    
      run: yarn

    - name: Build PDF
      run: yarn pdf

    - name: Create PDF output file
      run: mv 'Kelvin\'s Ethereum Book.pdf' book.pdf

    - name: Upload PDF to IPFS
      uses: aquiladev/ipfs-action@v0.2.1-alpha.4
      with:
        path: './book.pdf'        
